name: Export ECAD
on:
  push:

jobs:
  export-ecad:
    name: Export ECAD
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad8_auto:1.6.5
    steps:

    - name: Update system repositories, Install Required Libraries and Initialize git-lfs
      run: |
        apt update
        apt -y install git git-lfs zip librsvg2-bin imagemagick
        git lfs install

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        lfs: true


    - name: Update the PCBs with git hash
      run: |
        export COMMIT=$(git rev-parse --short HEAD)
        echo "COMMIT = ${COMMIT}"    
        echo "ref: ${{ github.ref }}"
        echo "default: ${{ env.default }}"
        find . -name '*.kicad_pcb' -exec sed -i "s!<<hash>>!${COMMIT}!" {} \;

    - name: Generate Export Files
      uses: INTI-CMNB/KiBot@v2_k8
      with:
          config: .github/workflows/scripts/kibot/config-2layer.kibot.yaml
          schema: holo-video-player.kicad_sch
          board: holo-video-player.kicad_pcb
          dir: output

    - name: Upload Export Files as Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: holo-video-player
        path: output
        if-no-files-found: error
        retention-days: 60

    - name: Generate Export Files
      uses: INTI-CMNB/KiBot@v2_k8
      with:
          config: .github/workflows/scripts/kibot/config-2layer.kibot.yaml
          schema: holo_ring/holo_ring.kicad_sch
          board: holo_ring/holo_ring.kicad_pcb
          dir: output-ring  

    - name: Upload Export Files as Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: holo-ring
        path: output-ring
        if-no-files-found: error
        retention-days: 60


